[font]
size = 14.0

[colors.primary]
foreground = "#ff8700"

[window.padding]
x = 4
y = 4

[font.normal]
family = "JetBrainsMonoNL Nerd Font Mono"
style = "Regular"

[font.bold]
family = "JetBrainsMonoNL Nerd Font Mono"
style = "Bold"

[font.italic]
family = "JetBrainsMonoNL Nerd Font Mono"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMonoNL Nerd Font Mono"
style = "Bold Italic"
