export PS1='%D{%H:%M:%S} %n@%m %1~ %# '

alias l='ls -lhGA --color=always'
alias zshrc='source ~/.zshrc'
alias venv='source venv/bin/activate'
# Obsidian vault - customize this path
# alias vault='cd "$HOME/Library/Mobile Documents/iCloud~md~obsidian/Documents/YOUR_VAULT"'
alias python='python3'
alias pip='pip3'

alias sync='launchctl bootout gui/$(id -u) ~/Library/LaunchAgents/com.user.sync_all.plist 2>/dev/null; launchctl bootstrap gui/$(id -u) ~/Library/LaunchAgents/com.user.sync_all.plist'
alias unsync='launchctl bootout gui/$(id -u) ~/Library/LaunchAgents/com.user.sync_all.plist'

export PATH="$HOME/.config/scripts:$HOME/scripts:$(brew --prefix mtr)/sbin:$PATH"
