export PS1='%D{%H:%M:%S} %n@%m %1~ %# '

alias l='ls -lhGA --color=always'
alias zshrc='source ~/.zshrc'
alias venv='source venv/bin/activate'
alias python='python3'
alias pip='pip3'

export PATH="$HOME/scripts:$PATH"
command -v brew &>/dev/null && export PATH="$(brew --prefix mtr)/sbin:$PATH"

[ -f ~/.secrets ] && source ~/.secrets

# Machine-specific additions (linked by dotfiles install/<profile>.sh)
[ -f ~/.config/shell/local ] && source ~/.config/shell/local
