[LightDM]

[Seat:*]
greeter-session=pi-greeter
greeter-hide-users=false
user-session=LXDE-pi-x
display-setup-script=/usr/share/dispsetup.sh
autologin-user=whf
autologin-session=LXDE-pi-x

[XDMCPServer]

[VNCServer]
