set -g mouse on
set -g history-limit 100000
setw -g mode-keys vi
bind r source-file ~/.tmux.conf \; display-message "tmux config reloaded"

# Status bar
set -g status-interval 5
set -g status-style 'bg=colour235 fg=colour250'
set -g window-status-current-style 'fg=colour208'
set -g pane-border-style 'fg=colour208'
set -g pane-active-border-style 'fg=colour208'

set -g status-left '#[fg=colour208] #H  #[fg=colour208]#(hostname -I | tr " " "\n" | grep -v "^100\." | head -1)  #[fg=colour208]#S  #[fg=colour208]#{=-35:pane_current_path}#(~/.tmux/git.sh #{pane_current_path}) #[default] '
set -g status-left-length 100

set -g status-right '#[fg=colour208]#(~/.tmux/ram.sh)  #[fg=colour208]#(~/.tmux/disk.sh)  #[fg=colour208]#(~/.tmux/cpu.sh)  #[fg=colour208]#(~/.tmux/temp.sh)  #[fg=colour208]#(cat /proc/loadavg | cut -d" " -f1)  #[fg=colour208]#(ps -e --no-headers -o comm | grep -vc "^\[")  #[fg=colour208]#(~/.tmux/uptime.sh) '
set -g status-right-length 160
