set -g mouse on
set -g history-limit 100000
setw -g mode-keys vi
bind r source-file ~/.tmux.conf \; display-message "tmux config reloaded"

# Status bar
set -g status-interval 5
set -g status-style 'bg=colour235 fg=colour250'


set -g status-left '#[fg=colour208,bold] #H #[default] '
set -g status-left-length 40

set -g status-right '#[fg=colour208]#{=-35:pane_current_path}#[fg=colour208] #(~/.tmux/git.sh #{pane_current_path}) #[fg=colour244]| #[fg=colour208]#(~/.tmux/ram.sh) #[fg=colour244]| #[fg=colour208]#(~/.tmux/temp.sh) #[fg=colour244]| #[fg=colour208]#(cat /proc/loadavg | cut -d" " -f1) #[fg=colour244]| #[fg=colour208]#(~/.tmux/uptime.sh) '
set -g status-right-length 160
