config_version	1.2
snapshot_root	/media/__USER__/BACKUP/
no_create_root	1

cmd_rsync	/usr/bin/rsync
cmd_cp	/bin/cp
cmd_rm	/bin/rm
cmd_logger	/usr/bin/logger
cmd_du	/usr/bin/du
cmd_rsnapshot_diff	/usr/bin/rsnapshot-diff

retain	weekly	30

rsync_short_args	-a
rsync_long_args	--delete --numeric-ids --relative --delete-excluded

exclude	/dev/*
exclude	/proc/*
exclude	/sys/*
exclude	/run/*
exclude	/tmp/*
exclude	/mnt/*
exclude	/media/*
exclude	/lost+found
exclude	/home/*/.cache/**

backup	/	rootfs/
